apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: archainia-wildcard-cert
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # ClusterIssuer 생성 후 실행
spec:
  secretName: archainia-wildcard-tls
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - archainia.app
    - "*.archainia.app"
  issuerRef:
    name: letsencrypt-issuer-archainia-app
    kind: ClusterIssuer

