persistence:
  defaultClass: true              # Longhorn을 클러스터의 기본 StorageClass로 설정
  defaultFsType: ext4             # PVC 생성 시 디스크 포맷 (ext4 권장, xfs도 가능)
  reclaimPolicy: Delete           # PVC 삭제 시 PV도 같이 삭제 (Retain으로 두면 PV는 남김)

defaultSettings:
  upgradeChecker: true    
  defaultReplicaCount: '{"v1":"1","v2":"1"}'  # 기본 복제본 수
  storageMinimalAvailablePercentage: "10"    # 디스크 최소 여유 공간이 25% 미만이면 스케줄링 안 함

service:
  ui:
    type: LoadBalancer             # Longhorn UI를 LoadBalancer로 노출 (MetalLB가 External-IP 할당)
    port: 80                       # Longhorn UI 접근 포트