apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tenant-loki-creds-secret
  namespace: tenant-loki
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Tenant 생성 전에 Secret이 먼저 있어야 함
spec:
  encryptedData:
    config.env: AgCY71+8szHTcksM+OWqmHF7ls32fB+PDxP4TfwzYylDCd9Uj9Sfs9E5mMYNXEpg5cQFd6eWW7eNJPk68GeB7pGdy6yHPE6kBc49XrJpcbMnCcxTKtvDF7aG2aBs6+4UJOseOz7Gj8XZRz4SmcK2VtgH+MoJ/ww51fVQdchn9cj9jjPQNsUYtyxQVRwgVSbW8jUzvyghPuZ4UV7ivaa2n6aeHacFXOLiWSMyCcQYT6VgOAo9ukesAmMjH9eJjuqsHu0ksMC2yaIYbIUOQ0MpwhwluOK+RP62VB1yMFOwEO+oDQi0fsNcB/qbnNrOJkak0MOAqn82679xFGdIbEYVaBftqZMAn9ellYWfGXtx+D6eH3xtVT5h1m1PpD3UmFiZNdY9cIFB18PIFYLu7ySlOdo+NxVpEWgg1EZCBAOftae6ISzXAwEtdtognvtxcVDKSt7URZAWG9MJQ4l5ZDNLAGcGlIU6WtFLzF73+6BJSp/vCn8twjMi985rq3Bq9iXhDThBIFjPckzvcwGalRBslfW2uFhN65QNF+Tfs8QGzlZRllUdeBaEz4sQAgD7vk52qhgWYlurwbKsOmn10BmuvDTy/mG/t42yR8AGZDYwHSn+fEbhWewwiO8nOiWPuu0ues/xxEkpG3R3W/VWsY92h6FjkosYN1wqD2VPsZbAJI8fvf7RWXPzvlpEswELu2gM6cMeNnw/h34tMKs1rau6qUqSL+VnmfH00uywm2wR8uzLqOy7C2H4CUwyBsvbCi7fg6TNF087mJ68c8Pt446Ju6+ZswF51xL1y3Pe
  template:
    metadata:
      name: tenant-loki-creds-secret
      namespace: tenant-loki
    type: Opaque

