apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-b-ingress
  namespace: production
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - service-b.archainia.app
      secretName: archainia-wildcard-tls

  rules:
    - host: service-b.archainia.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-b
                port:
                  number: 8080

