apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: service-b-env-secret
  namespace: production
spec:
  encryptedData:
    .env: AgCffiV/tnKiuHfjxqsF5pM1/vMNfIF3/LMQv9+cMOJGsgBq80RVxuW/ONc8mP/vMfjf1qGhy6yOiPXQg+pFB+bF8PVzIz9BZBxQquehMfAAS6Z0XlzjdTE/odbxwsqlAJprURhMmTCth6yoLELf9sqRs0lrP83mqY0fXF+D7pA6rN/sfAhKHpbZtNciaaeT8Y6NBxuJuS9HhIuNE1zpNyO+aujWT5DsUXrsbUGrmnwxwED3ImLlGal/vLunCVRnDvl7PJO7MDzXLsfMh0TOSI/TUQQTZEZBSo7XDlNLmkLdDS5HUk6fuqKF5BpQQokFZgzI1kGag43bu3Sv/idmLsZqpZ54tYhR9WAaCdQio9Tjp3aZ4QByn8JvhUijU5adrpr9cyff+cYEEVcNSAH+FAiWn9IVST5n60+9pG5YiQ3dk2G2xZz1n0x6QV/0hmZPlaAZwYdLiYv7dhxMf8SkMi3l0Vxb74Dlnee3iY2qsCPqUsZXkwxiv919O/bEcgh10y9WGMQQ0jOWkMxNdm7wHuzSbmY98By+i+Uyh5pDdl88JmcEUEdNTDRt9yMm7uozIKxl5WkD/FGLZZT/6Eem7dpRXdy/A756JjknAEF1PI3Etagit8wlcLPh0wCWbH8FtBICDFJsIeEUYd7azDOderFXMon2mjesoaiWVN5ycxBX7DHlcmNQ6u+rho1T6o5x855teWO/1kzllIXFq9o5ZrXBgEx20fNCQx9TlH18+8B2gdF2TDuc/ZvO3aDlN6r9SGBzoUH7Sww89TObD9fEAA2xabsTwMApVORiC9Gdl55B8QST+2ciJUco0g==
  template:
    metadata:
      name: service-b-env-secret
      namespace: production
    type: Opaque

