apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-b-env-secret
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    .env: AgBMcT+Mm8r01d0+h8Vwol2Y5IWSrBN5PLNt39gW7qNjmXo6OHkXcsNTuzofpfwtTKS55L0cPXKP/wiwKgEC1bcQZiPOqxiuLzYUME3timl+mBoUK5NjLXf0DQd7r5a3THJUgW6TlrtB3KARnMDEolkoToHiizEdNHVTwvCvvi/zhbIdbod22SOYsw//hEczjkn99EqF2+g56f0qpCv1t4lANjslChFKkuf+sU70Hxr7x3a4qtRFEeZ7GW7J85fkH+4XuxA4/EkWfJ46OFeuYiMEds8YQWfiCHOBXHsIwZtxSiCJC6INMevgh3uMvyG4XoEDdzbyvB4OMIxxRJIAh8JHY4JLoUzPzac+hbLUo7/OanYXPeRQbYbrYt5UTSLE9vyGEN1Ja3kf2OXjsjzTmv0QzvJejTAE/Csr++4752WZLf3xp4X/osJDYyCRxfCKmF+lic4Er+ZsGQfaHxdAh6SmN/Ma3lOkFjYH1XFABcuA4FFdBWMorcyJQivGRNUZ+uarI2G39mquKDtc4+MtI2xXccXOdnQhYZyVI1q9a4RKsgXV9vHSHizCbw3u/mdZaJzRmV4uL4LaAi9lI90YfQUUMwBC+GkI0mjp+HxQiOAnpblY22pXSrjDbiVzyIjjijpWANdSJZ4JhH1GS7vbztGL1DzYq1JaGe9OO2QUYRkbBUZKMtXG0Wb5ipvDozTnhuEntmty9kLNSZQPBqz0OMvbig2iqYF4BWaGsGEcY82tq0n4S1O7RhmxVUdbbJ4dOk9fYkyfR0LpNtQF9BDWJ7aGExZoQPXos7+3UQSRQsT3aVRfrJlwBQ2akXA4az8iQ8UymQ==
  template:
    metadata:
      name: service-b-env-secret
      namespace: production
    type: Opaque
