apiVersion: v1
data:
  tls.crt: # input your tls.crt
  tls.key: # input your tls.key
kind: Secret
metadata:
  creationTimestamp: "2025-11-21T08:20:15Z"
  generateName: sealed-secrets-key
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
  name: sealed-secrets-keygstf7
  namespace: sealed-secrets
  resourceVersion: "7453"
  uid: ae402302-7d2b-4ce1-98ea-4b9282b3dcba
type: kubernetes.io/tls