apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubed
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-structure
  sources:
    - repoURL: https://charts.appscode.com/stable/
      chart: kubed
      targetRevision: v0.13.2
      helm:
        values: |
          kubed:
            # operator 실행 설정
            operator:
              registry: appscode
              repository: kubed
              tag: v0.13.2
          # Secret Sync 기능 활성화 (기본값이지만 명시)
          enableConfigSyncer: true
          # 불필요한 기능 비활성화 (선택사항)
          enableAnalytics: false
    - repoURL: https://github.com/ong-ar/k8s-op
      path: git-ops/infra/kubed
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kubed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

