apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-a
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: services
  source:
    repoURL: https://github.com/ong-ar/k8s-op.git
    targetRevision: HEAD
    path: git-ops/apps/service-a
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

