apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: service-a-env-secret
  namespace: production
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    .env: AgArsSn6c/8pR3WZF8Ws/w1nvvsHfssM7MmPT0dPCXklILR5OpGKNS0rJEV1mggKN3SPJqYQihJjlCznhXFCpeSIUXQ1MVd4kxL334EbWbM46JCCIFbreTweRXT/THRAEgev9UG7KREQ87/wggzx+MucvOHzvu8Bf7MJKLIreXEAvDd4Az/jw64SHpm1iW9IVJkl3QUmZCcv67RfAnPUcQmQRM4MNOw6buuAPBA9UbCTmuOBuCwRbHR+gJamWZjJVijQ8la5sSO5jFWJBmSAcObmhBNFMUB+wVGPzsH9CaSe7sRF9CqDLMaPqaydUNZmh20rLhYzNZwljd0povHzCxYsgVPrrEuBJqI0HbjNX6axukgpV+SiTiJaN2K2HwOSvIgdV6Ts0L1nTHOYiy3EpGHwe/wDcUz8IUEU2zTEcEbUuTX1mpPMqdy7k6SkBZRtQuafCOME6M/v36Vh2Y4ixoiDD22+OT0gdGCp4otyNXB9kBYUHuywfcWMEczzZsR5JcjRjageP+is/r6JSyy79z5GZ7tYhIhPqzNHXv3kFsyWIsemghU2PnqB5CGzzayR4xIKKfQbom2/xIgzlwDP7BCPp9G92wuV92wyBsl/aHrcIHXUgiuLEO8vkeKCajsj3QI41iJLcYgdKuhN50+VXKsnnyzbRKIR3nHICuV/hdbNHDQSkwfi70PAWnmDe4ILzt2q82BpRzJj7GuNWhxiQHIAG9Ypec1QmMMVn+l/D27Z2o61nCvxIz47m4YpSdmpJFkREu0feMTfTxxBaMK3zyNSPO2QSi/6z9PO5WVeMBDOzobBOMTynbno
  template:
    metadata:
      name: service-a-env-secret
      namespace: production
    type: Opaque
