apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tenant-loki-creds-secret
  namespace: tenant-loki
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    config.env: AgAxFYxgMUtHa6zZ1H5AsPluOrk0WdIwC1ZHmbamYQK3Ly3UbLLJgmRNR+RK2Umly7E6OdI96ef7Kt6A0Fbpo1H1LlsSMeK4NoJuEp+ws5cJ7ZqOopqRgEYn4WxbwyXroEMzVVAk/UOTL4bbPshTWYAn306ORD3/iJx5oqH44a+i4adYgVaAG89ehQWVvMgSOzUSiZQ8JnRKMabYroPk1RwKtdIp19DWfesbZlUtfjaGRlykGyUGyl8zxIE4niWSCfA5GwZWb76tfzRj7AYidT+t7TaIrxdiSjJGF94pq3DW771jPQierKvnPwnsC/wivmKHyvYIPQmadshHL49980nT84hoqY1gslAEIBvX4MCHLUcNbtGJpAZgi/NlSRbqOGaRUnSMgjRXou15bL+3AgqlrU1Ezv2KRJ923/FPRi6I0SXJ/2CUbbOS+MCjhuc4lC71SJrNVwaMn4NnG74WDo0GPLkKoluYSA4UIxRMB4wITNpsGDKHOSYOQvi8rucQzjmnO6f7apEiAgG/uryqoe7RIjtoZ0aCXnU35eDAl6ygBzpdr53NNBIRiYYWR7l+D1KpMmo/bNJnfxDPZo/gjRu2JEmHrIFZyBzI6HOBwXIKsumTy2YKGhlM1PzybUoB4pwFHaPkmMGQGotFd3LZLx2kxikKErpNqx3KUvsJCTvcIBeRDX+nhpxswy4UlzUB1bHeKFzboVhm+ZbWHFF03R8slmjuBg/QPpd+SY1l50TeF5CtPE3nI5TW7VIhSMkTbLme/4qd2pgBgY7cP1HFlSQac/CPLNsvSzY9
  template:
    metadata:
      name: tenant-loki-creds-secret
      namespace: tenant-loki
    type: Opaque
